version: "3"
services:
  chat:
    build: ./chat
    depends_on:
      - mosquitto
      - api
    ports:
      - 8080:8080
    networks:
      - mqtt_net
      - api_front_net
      - prom_net

  api:
    build: ./api
    ports:
      - 8081:8081
    depends_on:
      - db
    networks:
      - api_front_net
      - db_net

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    ports:
      - 1883:1883
    networks:
      - mqtt_net

  db-adapter:
    build: ./db-adapter
    depends_on:
      - db
      - mosquitto
    environment:
      - DEBUG_DATA_FLOW=${DEBUG_DATA_FLOW}
    networks:
      - mqtt_net
      - db_net

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=chat
    volumes:
      - ./mysql/config:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
    networks:
      - db_net

  prometheus:
    image: prom/prometheus:latest
    depends_on:
      - node-exporter
    volumes:
      - ./prometheus/config:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    networks:
      - prom_net

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - 9100:9100
    networks:
      - prom_net

  grafana:
    build: ./grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    networks:
      - mqtt_net
      - db_net
      - api_front_net
      - prom_net

  # For testing purposes
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8089:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - db_net

networks:
  mqtt_net:
  db_net:
  api_front_net:
  prom_net: