scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090', 'node-exporter:9100']

  - job_name: 'chat_stats'
    scrape_interval: 3s
    dns_sd_configs:
      - names: ['chat']
        port: 8080
        type: A
        refresh_interval: 5s